name: country_phone_field_example
description: "Demonstrates the country_phone_field package."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.12.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  country_phone_field:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
